Repository justeattakeaway/httpclient-interception, pull requests merged in 2021-04, with the labels that each got.

#317 fix some spelling
  src/HttpClientInterception/HttpRequestInterceptionBuilderExtensions.cs
  src/HttpClientInterception/NewtonsoftJsonExtensions.cs
  src/HttpClientInterception/SystemTextJsonExtensions.cs
  tests/HttpClientInterception.Tests/InterceptingHttpMessageHandlerTests.cs
Labels: bug, documentation

#319 allow nulls for some params
  src/HttpClientInterception/HttpRequestInterceptionBuilder.cs
  src/HttpClientInterception/HttpRequestInterceptionBuilderExtensions.cs
  src/HttpClientInterception/PublicAPI.Shipped.txt
Labels: bug, enhancement

#322 Extend bundle test
  tests/HttpClientInterception.Tests/Bundles/BundleExtensionsTests.cs
  tests/HttpClientInterception.Tests/Bundles/templated-bundle-json.json
Labels: enhancement

#318 fix multi enumeration bug
  src/HttpClientInterception/BundleExtensions.cs
Labels: enhancement

#323 fix broken docs ref
  samples/SampleApp.Tests/HttpServerFixture.cs
Labels: bug

#324 use a named tuple
  src/HttpClientInterception/HttpClientInterceptorOptions.cs
Labels: enhancement
