Repository justeattakeaway/httpclient-interception, pull requests merged in 2022-11, with the labels that each got.

#475 Support dynamic HTTP headers
  Directory.Build.props
  Directory.Build.targets
  src/HttpClientInterception/HttpRequestInterceptionBuilder.cs
  src/HttpClientInterception/PublicAPI.Shipped.txt
  tests/HttpClientInterception.Tests/Examples.cs
  tests/HttpClientInterception.Tests/HttpRequestInterceptionBuilderTests.cs
Labels: bug, enhancement

#495 Fix bundle templating with no values in bundle
  src/HttpClientInterception/Bundles/BundleItemConverter.cs
  tests/HttpClientInterception.Tests/Bundles/BundleExtensionsTests.cs
  tests/HttpClientInterception.Tests/Bundles/templated-bundle-json-no-parameters.json
Labels: bug

#497 Update Benchmarks
  README.md
  tests/HttpClientInterception.Benchmarks/InterceptionBenchmarks.cs
Labels: documentation

#486 Improve additional matching for requests with the same URL
  src/HttpClientInterception/DelegateHelpers.cs
  src/HttpClientInterception/HttpRequestInterceptionBuilder.cs
  src/HttpClientInterception/PublicAPI.Shipped.txt
  tests/HttpClientInterception.Tests/Examples.cs
  tests/HttpClientInterception.Tests/HttpRequestInterceptionBuilderTests.cs
Labels: enhancement
